import path from "node:path"
import { log } from "../lib/logger.ts"

export interface KeygenOptions {
  /** Base path — we write `<base>.key` (PKCS#8) and `<base>.pub` (base64 raw). */
  out: string
  /** Overwrite existing files instead of failing. */
  force?: boolean
}

/** Generate an Ed25519 keypair for the auto-updater. */
export async function keygen(opts: KeygenOptions): Promise<void> {
  const privPath = path.resolve(`${opts.out}.key`)
  const pubPath = path.resolve(`${opts.out}.pub`)

  if (!opts.force) {
    for (const p of [privPath, pubPath]) {
      if (await Bun.file(p).exists()) {
        log.error(`${path.relative(process.cwd(), p)} already exists (use --force to overwrite)`)
        process.exit(1)
      }
    }
  }

  const { publicKey, privateKey } = (await crypto.subtle.generateKey("Ed25519", true, [
    "sign",
    "verify",
  ])) as CryptoKeyPair

  // PKCS#8 DER for the private key (WebCrypto won't export raw private keys).
  const privDer = await crypto.subtle.exportKey("pkcs8", privateKey)
  // Raw 32-byte public key — matches VerifyingKey::from_bytes() in the host.
  const pubRaw = await crypto.subtle.exportKey("raw", publicKey)

  await Bun.write(privPath, privDer)
  await Bun.write(pubPath, `${Buffer.from(pubRaw).toString("base64")}\n`)

  log.blank()
  log.success(`Private key -> ${log.cyan(path.relative(process.cwd(), privPath))}`)
  log.success(`Public key  -> ${log.cyan(path.relative(process.cwd(), pubPath))}`)
  log.blank()
  log.info("Keep the private key secret. Embed the public key in your app's source:")
  log.dim(`  const UPDATER_PUB_KEY = "${Buffer.from(pubRaw).toString("base64")}"`)
  log.blank()
}

export interface SignOptions {
  file: string
  key: string
  /** If set, write the signature here instead of stdout. */
  out?: string
}

/** Sign a file with an Ed25519 private key generated by `tynd keygen`. */
export async function sign(opts: SignOptions): Promise<void> {
  const keyPath = path.resolve(opts.key)
  const filePath = path.resolve(opts.file)

  if (!(await Bun.file(keyPath).exists())) {
    log.error(`key not found: ${path.relative(process.cwd(), keyPath)}`)
    process.exit(1)
  }
  if (!(await Bun.file(filePath).exists())) {
    log.error(`file not found: ${path.relative(process.cwd(), filePath)}`)
    process.exit(1)
  }

  const pkcs8 = await Bun.file(keyPath).bytes()
  const privateKey = await crypto.subtle.importKey("pkcs8", pkcs8, "Ed25519", false, ["sign"])
  const payload = await Bun.file(filePath).bytes()
  const sigBytes = await crypto.subtle.sign("Ed25519", privateKey, payload)
  const signature = `${Buffer.from(sigBytes).toString("base64")}\n`

  if (opts.out) {
    const outPath = path.resolve(opts.out)
    await Bun.write(outPath, signature)
    log.success(`Signature -> ${log.cyan(path.relative(process.cwd(), outPath))}`)
  } else {
    process.stdout.write(signature)
  }
}
