import { fileURLToPath } from "url";
import { mkdirSync } from "fs";
import { readdir } from "fs/promises";
import path from "path";
import { spinner, intro, outro } from "@clack/prompts";
import { resolveTarget, bunTarget } from "../utils/targets";
import { loadConfig, readPackageName } from "../utils/config";
import { downloadHost } from "../utils/download";
import { patchWindowsSubsystem } from "../utils/pe";
import { generatePortable, generateInstaller } from "../utils/installers";
import { resolveIconPath, generateNativeIcons } from "../utils/icon";
import { injectIcon } from "../utils/rcedit";
import { signIfConfigured, signAllArtifacts } from "../utils/sign";
import { log, c } from "../utils/colors";

/** Recursively list all files in a directory, returning relative paths. */
async function scanDir(dir: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    if (e.isDirectory()) {
      files.push(...await scanDir(path.join(dir, e.name), rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

export async function runBuild(args: string[]) {
  const target  = resolveTarget(args);
  const ext     = target.startsWith("windows") ? ".exe" : "";
  const startedAt = Date.now();

  intro(c.bold(`bunview build ${c.dim(`→ ${target}`)}`));

  const config   = await loadConfig();
  const cwd      = process.cwd();
  const outDir   = path.resolve(cwd, config.outDir ?? "release");
  const appName  = config.name ?? (await readPackageName(cwd)) ?? "app";
  const outBin   = path.join(outDir, `${appName}${ext}`);
  const entryAbs = path.resolve(cwd, config.entry);
  const tmpDir   = path.join(cwd, ".bunview-tmp");

  mkdirSync(outDir, { recursive: true });
  mkdirSync(tmpDir, { recursive: true });
  let icons: { ico?: string, icns?: string, png?: string } = {};
  const iconSrc = await resolveIconPath(cwd, config);
  if (iconSrc) {
    console.log(`[bunview] Found app icon: ${path.relative(cwd, iconSrc)}`);
    try {
      icons = await generateNativeIcons(iconSrc, path.join(tmpDir, "icons"));
    } catch (err) {
      console.warn(`[bunview] ⚠  Failed to process icons: ${err}`);
    }
  }

  // Remove stale binary so Bun can move the newly compiled file into place.
  // On Windows, the file may be locked by a running process or antivirus — kill + retry.
  if (await Bun.file(outBin).exists()) {
    if (process.platform === "win32") {
      // Kill any running instance of the app (silent — it may not be running)
      await Bun.spawn(["taskkill", "/F", "/IM", path.basename(outBin)],
        { stdout: "pipe", stderr: "pipe" }).exited;
    }
    // Retry up to 5× with 500 ms delay to let antivirus/OS release the lock
    const { unlink } = await import("fs/promises");
    for (let attempt = 0; attempt < 5; attempt++) {
      try { await unlink(outBin); break; } catch {
        if (attempt === 4) {
          console.error(`[bunview] ❌ Cannot replace ${path.basename(outBin)} — close the app and retry.`);
          process.exit(1);
        }
        await Bun.sleep(500);
      }
    }
  }
  const bunviewRoot = fileURLToPath(new URL("../../", import.meta.url));
  const hostOriginal = path.join(bunviewRoot, "bin", target, `webview-host${ext}`);
  if (!await Bun.file(hostOriginal).exists()) await downloadHost(target, hostOriginal, ext);
  if (!await Bun.file(hostOriginal).exists()) {
    console.error(`[bunview] ❌ webview-host not found for "${target}".`);
    process.exit(1);
  }

  // Copy host to tmpDir to customize it (icon, etc.) without modifying the original
  const hostSrc = path.join(tmpDir, `webview-host${ext}`);
  const { copyFileSync } = await import("fs");
  copyFileSync(hostOriginal, hostSrc);

  if (target.startsWith("windows") && icons.ico) {
    await injectIcon(hostSrc, icons.ico);
    // Also patch subsystem just in case the original was console
    await patchWindowsSubsystem(hostSrc);
  }
  const frontendDir = config.frontend ? path.resolve(cwd, config.frontend) : null;
  let fileCount = 0;
  const imports: string[]    = [];
  const mapEntries: string[] = [];

  imports.push(`import _host from ${JSON.stringify(hostSrc.replace(/\\/g, "/"))} with { type: "file" };`);

  if (frontendDir && await Bun.file(path.join(frontendDir, "index.html")).exists()) {
    const files = await scanDir(frontendDir);
    for (const rel of files) {
      const abs     = path.join(frontendDir, rel).replace(/\\/g, "/");
      const varName = `_f${fileCount}`;
      const urlPath = "/" + rel.replace(/\\/g, "/");
      imports.push(`import ${varName} from ${JSON.stringify(abs)} with { type: "file" };`);
      mapEntries.push(`  ${JSON.stringify(urlPath)}: ${varName},`);
      fileCount++;
    }
  }

  const embedCode = [
    "// Auto-generated by bunview build — do not edit",
    ...imports,
    "",
    `(globalThis as any).__BUNVIEW_EMBEDDED__ = {`,
    `  host: _host,`,
    `  files: {`,
    ...mapEntries,
    `  },`,
    `};`,
    "",
    `await import(${JSON.stringify(entryAbs.replace(/\\/g, "/"))});`,
  ].join("\n");

  const wrapperPath = path.join(tmpDir, "_bunview_entry.ts");
  await Bun.write(wrapperPath, embedCode);

  console.log(`[bunview] Embedding ${fileCount} frontend files + webview-host`);
  console.log(`[bunview] Compiling → ${path.relative(cwd, outBin)}`);
  const compileProc = Bun.spawn(
    ["bun", "build", "--compile", `--target=${bunTarget(target)}`, wrapperPath, `--outfile=${outBin}`],
    { stdout: "inherit", stderr: "inherit" },
  );
  const compileExit = await compileProc.exited;
  if (compileExit !== 0) {
    try { (await import("fs/promises")).rm(tmpDir, { recursive: true }); } catch {}
    process.exit(compileExit);
  }

  // Patch Windows PE: CONSOLE → WINDOWS GUI (no terminal on double-click) + Icon
  if (target.startsWith("windows")) {
    await patchWindowsSubsystem(outBin);
    if (icons.ico) {
      await injectIcon(outBin, icons.ico);
    }
    console.log(`[bunview] Patched PE binary (subsystem + icon)`);
  }

  // Code signing — must run after every binary mutation (PE patch / icon inject).
  // Main binary is signed without notarization (notarize the distribution artifacts instead).
  await signIfConfigured(outBin, target, config, false);

  const sizeMB = (Bun.file(outBin).size / 1024 / 1024).toFixed(1);
  const relOut  = path.relative(cwd, outBin).replace(/\\/g, "/");
  const runCmd  = target.startsWith("windows") ? `.\\${relOut.replace(/\//g, "\\")}` : `./${relOut}`;

  log.ok(`${path.relative(cwd, outBin)} (${sizeMB} MB)`);

  const skipPortable  = args.includes("--skip-portable");
  const skipInstaller = args.includes("--skip-installer");

  const schemeName = config.urlScheme?.name;

  if (!skipPortable) {
    const portSp = spinner();
    portSp.start("Generating portable archive…");
    await generatePortable(outBin, appName, target, outDir, icons, schemeName, config.fileAssociations);
    portSp.stop("Portable ready");
  }

  if (!skipInstaller) {
    const instSp = spinner();
    instSp.start("Generating installer…");
    await generateInstaller(outBin, appName, target, outDir, icons, schemeName, config.fileAssociations);
    instSp.stop("Installer ready");
  }

  if (config.codeSigning) {
    const signSp = spinner();
    signSp.start("Signing distribution artifacts…");
    await signAllArtifacts(outDir, appName, target, config);
    signSp.stop("Signed");
  }

  try { (await import("fs/promises")).rm(tmpDir, { recursive: true }); } catch {}

  const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);
  outro(`${c.green("✓")} Build complete in ${c.bold(`${elapsed}s`)} — run: ${c.cyan(runCmd)}`);
}
