export default {
  app: "app",
  window: "tyndWindow",
  monitor: "monitors",
  dialog: "dialog",
  clipboard: "clipboard",
  shell: "shell",
  notification: "notification",
  tray: "tray",
  menu: "menu",
  shortcuts: "shortcuts",
  fs: "fs",
  path: "path",
  os: "os",
  process: "process",
  sidecar: "sidecar",
  store: "store",
  sql: "sql",
  http: "http",
  websocket: "websocket",
  terminal: "terminal",
  workers: "workers",
  compute: "compute",
  keyring: "keyring",
  autolaunch: "autolaunch",
  "single-instance": "singleInstance",
  updater: "updater",
  log: "log",
  power: "power",
  security: "security",
  web: "web (globals)",
};
