export default {
  "frontend-frameworks": "Frontend Frameworks",
  "backend-rpc": "Backend RPC",
  streaming: "Streaming RPC",
  "multi-window": "Multi-Window",
  "binary-data": "Binary Data",
  sidecars: "Sidecars",
  persistence: "Persistence",
  "auto-updates": "Auto-Updates",
  "code-signing": "Code Signing",
  bundling: "Bundling & Distribution",
  "single-instance": "Single Instance",
  "deep-linking": "Deep Linking",
  "keyboard-shortcuts": "Keyboard Shortcuts",
  "icons-branding": "Icons & Branding",
  i18n: "Internationalization",
  accessibility: "Accessibility",
  testing: "Testing",
  performance: "Performance",
  debugging: "Debugging",
  "migrate-from-tauri": "Migrate from Tauri",
  "migrate-from-electron": "Migrate from Electron",
};
